/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int ABSTRACT = 8;
  int BOOLEAN = 9;
  int BREAK = 10;
  int BYTE = 11;
  int CASE = 12;
  int CATCH = 13;
  int CHAR = 14;
  int CLASS = 15;
  int CONST = 16;
  int CONTINUE = 17;
  int DO = 18;
  int DOUBLE = 19;
  int ELSE = 20;
  int EXTENDS = 21;
  int FINAL = 22;
  int FINALLY = 23;
  int FLOAT = 24;
  int FALSE = 25;
  int FOR = 26;
  int GOTO = 27;
  int IF = 28;
  int IMPLEMENTS = 29;
  int IMPORT = 30;
  int INSTANCEOF = 31;
  int INT = 32;
  int INTERFACE = 33;
  int LONG = 34;
  int NATIVE = 35;
  int NEW = 36;
  int NULL = 37;
  int PACKAGE = 38;
  int PRIVATE = 39;
  int PROTECTED = 40;
  int PUBLIC = 41;
  int RETURN = 42;
  int SHORT = 43;
  int STATIC = 44;
  int STRICTFP = 45;
  int SUPER = 46;
  int SWITCH = 47;
  int SYNCHRONIZED = 48;
  int THIS = 49;
  int THROW = 50;
  int THROWS = 51;
  int TRANSIENT = 52;
  int TRY = 53;
  int TRUE = 54;
  int VOID = 55;
  int VOLATILE = 56;
  int WHILE = 57;
  int PLUS = 58;
  int ASSIGN = 59;
  int EQUAL = 60;
  int GT = 61;
  int GT_EQUAL = 62;
  int INC = 63;
  int AND = 64;
  int AND_ASSIGN = 65;
  int LAND = 66;
  int LT = 67;
  int LE = 68;
  int BITXOR = 69;
  int BITXOR_ASSIGN = 70;
  int LNOT = 71;
  int NOT_EQUAL = 72;
  int MINUS = 73;
  int MINUS_ASSIGN = 74;
  int DEC = 75;
  int PLUS_ASSIGN = 76;
  int STAR = 77;
  int STAR_ASSIGN = 78;
  int DIV = 79;
  int DIV_ASSIGN = 80;
  int REM = 81;
  int REM_ASSIGN = 82;
  int SSLEFT = 83;
  int SSL_ASSIGN = 84;
  int SSRIGHT = 85;
  int SSR_ASSIGN = 86;
  int USRIGHT = 87;
  int USR_ASSIGN = 88;
  int COMPLEMENT = 89;
  int BTOR = 90;
  int BTOR_ASSIGN = 91;
  int LOR = 92;
  int QUESTION = 93;
  int LPAREN = 94;
  int RPAREN = 95;
  int LCURLY = 96;
  int RCURLY = 97;
  int LBRACK = 98;
  int RBRACK = 99;
  int SEMI = 100;
  int COMMA = 101;
  int DOT = 102;
  int COLON = 103;
  int IDENTIFIER = 104;
  int LETTER = 105;
  int DIGIT = 106;
  int NON_ZERO_DIGIT = 107;
  int INT_LITERAL = 108;
  int CHAR_LITERAL = 109;
  int STRING_LITERAL = 110;
  int ESC = 111;
  int DOUBLE_LITERAL = 112;
  int ERROR = 113;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"false\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"true\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"++\"",
    "\"&\"",
    "\"&=\"",
    "\"&&\"",
    "\"<\"",
    "\"<=\"",
    "\"^\"",
    "\"^=\"",
    "\"!\"",
    "\"!=\"",
    "\"-\"",
    "\"-=\"",
    "\"--\"",
    "\"+=\"",
    "\"*\"",
    "\"*=\"",
    "\"/\"",
    "\"/=\"",
    "\"%\"",
    "\"%=\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>\"",
    "\">>=\"",
    "\">>>\"",
    "\">>>=\"",
    "\"~\"",
    "\"|\"",
    "\"|=\"",
    "\"||\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<DOUBLE_LITERAL>",
    "<ERROR>",
  };

}
