/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int BREAK = 9;
  int BYTE = 10;
  int CASE = 11;
  int CATCH = 12;
  int CHAR = 13;
  int CLASS = 14;
  int CONST = 15;
  int CONTINUE = 16;
  int DO = 17;
  int DOUBLE = 18;
  int ELSE = 19;
  int EXTENDS = 20;
  int FINAL = 21;
  int FINALLY = 22;
  int FLOAT = 23;
  int FALSE = 24;
  int FOR = 25;
  int GOTO = 26;
  int IF = 27;
  int IMPLEMENTS = 28;
  int IMPORT = 29;
  int INSTANCEOF = 30;
  int INT = 31;
  int INTERFACE = 32;
  int LONG = 33;
  int NATIVE = 34;
  int NEW = 35;
  int NULL = 36;
  int PACKAGE = 37;
  int PRIVATE = 38;
  int PROTECTED = 39;
  int PUBLIC = 40;
  int RETURN = 41;
  int SHORT = 42;
  int STATIC = 43;
  int STRICTFP = 44;
  int SUPER = 45;
  int SWITCH = 46;
  int SYNCHRONIZED = 47;
  int THIS = 48;
  int THROW = 49;
  int THROWS = 50;
  int TRANSIENT = 51;
  int TRY = 52;
  int TRUE = 53;
  int VOID = 54;
  int VOLATILE = 55;
  int WHILE = 56;
  int PLUS = 57;
  int ASSIGN = 58;
  int EQUAL = 59;
  int GT = 60;
  int GT_EQUAL = 61;
  int INC = 62;
  int AND = 63;
  int AND_ASSIGN = 64;
  int LAND = 65;
  int LT = 66;
  int LE = 67;
  int BITXOR = 68;
  int BITXOR_ASSIGN = 69;
  int LNOT = 70;
  int NOT_EQUAL = 71;
  int MINUS = 72;
  int MINUS_ASSIGN = 73;
  int DEC = 74;
  int PLUS_ASSIGN = 75;
  int STAR = 76;
  int STAR_ASSIGN = 77;
  int DIV = 78;
  int DIV_ASSIGN = 79;
  int REM = 80;
  int REM_ASSIGN = 81;
  int SSLEFT = 82;
  int SSL_ASSIGN = 83;
  int SSRIGHT = 84;
  int SSR_ASSIGN = 85;
  int USRIGHT = 86;
  int USR_ASSIGN = 87;
  int COMPLEMENT = 88;
  int BITWISE_OR = 89;
  int BITWISE_OR_ASSIGN = 90;
  int LOGICAL_OR = 91;
  int QUESTION = 92;
  int LPAREN = 93;
  int RPAREN = 94;
  int LCURLY = 95;
  int RCURLY = 96;
  int LBRACK = 97;
  int RBRACK = 98;
  int SEMI = 99;
  int COMMA = 100;
  int DOT = 101;
  int COLON = 102;
  int IDENTIFIER = 103;
  int LETTER = 104;
  int DIGIT = 105;
  int NON_ZERO_DIGIT = 106;
  int EXPONENT = 107;
  int DOUBLE_END = 108;
  int DOUBLE_LITERAL = 109;
  int INT_LITERAL = 110;
  int CHAR_LITERAL = 111;
  int STRING_LITERAL = 112;
  int ESC = 113;
  int ERROR = 114;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"false\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"true\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"++\"",
    "\"&\"",
    "\"&=\"",
    "\"&&\"",
    "\"<\"",
    "\"<=\"",
    "\"^\"",
    "\"^=\"",
    "\"!\"",
    "\"!=\"",
    "\"-\"",
    "\"-=\"",
    "\"!-\"",
    "\"+=\"",
    "\"*\"",
    "\"*=\"",
    "\"/\"",
    "\"/=\"",
    "\"%\"",
    "\"%=\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>\"",
    "\">>=\"",
    "\">>>\"",
    "\">>>=\"",
    "\"~\"",
    "\"|\"",
    "\"|=\"",
    "\"||\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<EXPONENT>",
    "<DOUBLE_END>",
    "<DOUBLE_LITERAL>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
